server:
  port: 8081
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
    
#spring:
  #application:
    #name: 'ms-fornecedor'    #profiles:    #active: dev  #cloud:    #config:      #uri: http://localhost:8888        #jpa:    #hibernate:      #ddl-auto: update    #show-sql: true  #datasource:    #url: jdbc:mysql://localhost:3306/db_fornecedor?useTimezone=true&serverTimezone=UTC    #driver-class-name: com.mysql.jdbc.Driver    #password: root    #username: root        