server:
  port: 8081
spring:  datasource:    driver-class-name: org.h2.Driver    url: jdbc:h2:mem:db-fornecedor
    username: sa
    password:   h2:    console:      enabled: true
      path: /h2-console
    