
server:  port: 8888
  
spring:
 cloud:
    config:
      server:
       default-label: main
       git:
         uri: https://github.com/RodrigoFrancaBR/microservice-repo
         search-paths: fornecedor             
               
         